export const formControlNames = {
    first_name: 'first_name',
    last_name: 'last_name',
    year_of_birth: 'date_birth',
    sex: 'sex',
    payer: 'payer',
    father_name: 'father_name',
    mother_name: 'mother_name',
    married: 'married',
    spouse: 'spouse',
    phone_number: 'phone_number',
    email: 'email',
    address: 'address',
    jmbg: 'jmbg',
}

export const formLabels = {
    first_name: 'Ime',
    last_name: 'Prezime',
    year_of_birth: 'Datum rodjenja',
    sex: 'Spol',
    payer: 'Platiša',
    father_name: 'Ime oca',
    mother_name: 'Ime majke',
    married: 'U braku',
    spouse: 'Odaberi supružnika',
    phone_number: 'Broj telefona',
    email: 'Email',
    address: 'Adresa',
    jmbg: 'JMBG',
}
